name: Build and Deploy Programming Guides

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    # Set up GitHub Pages environment only for pushes to master
    environment:
      name: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'github-pages' || '' }}
      url: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && '${{ steps.deployment.outputs.page_url }}/latest/' || '' }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup mdBook 📥
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Install doxygen tools 🧱
        run: |-
          sudo apt-get install -y doxygen
          pip install esp-doxybook

      - name: Build docs 🔧
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            python3 ./.github/build_docs.py --pr-number ${{ github.event.pull_request.number }}
          else
            python3 ./.github/build_docs.py
          fi

      - name: Check Links 🔍
        uses: lycheeverse/lychee-action@v2
        with:
          # Check links in docs_build_output
          args: >-
            --no-progress
            --include-fragments
            './docs_build_output/**/*.html'
          # Fail the action if broken links are found
          fail: true

      # The following steps only run on push to master branch
      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v5

      - name: Prepare docs directory structure
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          mkdir -p gh-pages/latest
          cp -r docs_build_output/* gh-pages/latest/

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4

